version: '3'

services:
  gitouttahere:
    container_name: gitouttahere
    build: gitouttahere
    ports:
      - 9000:443
  
  monitctf:
    container_name: monitctf
    build: monitctf 
    ports:
      - 9100:2812
    restart: always

  cccrypto:
    container_name: cccrypto
    build: cccrypto 
    ports:
      - 9200:3100

  jarjarbinks:
    container_name: jarjarbinks
    build: jarjarbinks 
    ports:
      - 9300:8080

  ggrf:
    container_name: ggrf
    build: ggrf
    ports:
      - 9400:8080
